- name: Install Kali XFCE Desktop
  apt:
    name:
      - kali-desktop-xfce
    update_cache: yes
    state: present

- name: Create Desktop Directory
  become: true
  become_user: "{{ansible_user}}"
  file:
    path: /home/{{ansible_user}}/Desktop
    state: directory
    mode: 0755

- name: Copy over the Log4JCallback.java
  copy:
    src: Log4JCallback.java
    dest: /home/{{ansible_user}}/Log4JCallback.java
