---
- hosts: jump_host
  become: yes
  vars_files:
    #- server_secrets.enc
  roles:
    - nat_server
    - docker_server
    - guacamole_server

- hosts: kali_host
  become: yes
  vars_files:
    #- server_secrets.enc
  roles:
    - jndi_server
    - kali_desktop
    - vnc_server
